STR_DATE = 'date'
STR_DETAILS = 'details'
STR_ENACTMENTS_CSV = 'enactments.csv'
STR_ENACTMENTS_URL = 'http://iportal.rada.gov.ua/news/hpz8'
STR_NEWS_ITEM = 'news_item'
STR_LIST_ARCHIVE = 'list_archive'
STR_HREF = 'href'
STR_PAGE_NEXT = 'page-next'